name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        maven: [ '3.8.7', '3.9.0' ]
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Step 1 - Set java version = 11
      uses: actions/setup-java@v1
      with:
          java-version: '11'
          
    - name: step 2 - Set up a cache for maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: step 3 - Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: step 4 -  Maven Verify
      run: mvn -B clean verify
      
    - name: step 5 - Run tests with Maven
      run: mvn -B test --file pom.xml
      

