name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        maven: [ '3.9.0' ]
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Step 1 - Set java version = 11
      uses: actions/setup-java@v1
      with:
          java-version: '11'
          
    - name: step 2 - Set up a cache for maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: step 3 - Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: step 4 -  Maven Verify
      run: mvn -B clean verify
      
    - name: step 5 - Run tests with Maven
      run: mvn -B test --file pom.xml
    
  push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Login to DockerHub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Set outputs
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: codelabz/repository

        - name: Build and push the Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: codelabz/repository:backend-${{ steps.vars.outputs.sha_short }}
            labels: ${{ steps.meta.outputs.labels }}
      


